# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('localizacao', models.CharField(max_length=50)),
                ('h1_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h2_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h3_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h4_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h5_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h6_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h1_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h2_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h3_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h4_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h5_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h6_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h1_Noturno', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h2_Noturno', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h3_Noturno', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h4_Noturno', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ReservarMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora_Atual', models.DateTimeField()),
                ('horario_de_Entrada', models.CharField(choices=[('1° Horário - Manhã', '1° Horário - Manhã'), ('2° Horário - Manhã', '2° Horário - Manhã'), ('3° Horário - Manhã', '4° Horário - Manhã'), ('4° Horário - Manhã', '4° Horário - Manhã'), ('5° Horário - Manhã', '5° Horário - Manhã'), ('6° Horário - Manhã', '6° Horário - Manhã'), ('1° Horário - Tarde', '1° Horário - Tarde'), ('2° Horário - Tarde', '2° Horário - Tarde'), ('3° Horário - Tarde', '4° Horário - Tarde'), ('4° Horário - Tarde', '4° Horário - Tarde'), ('5° Horário - Tarde', '5° Horário - Tarde'), ('6° Horário - Tarde', '6° Horário - Tarde'), ('1° Horário - Noite', '1° Horário - Noite'), ('2° Horário - Noite', '2° Horário - Noite'), ('3° Horário - Noite', '3° Horário - Noite'), ('4° Horário - Noite', '4° Horário - Noite')], default='1° Horário - Manhã', max_length=18)),
                ('horario_de_Saida', models.CharField(choices=[('1° Horário - Manhã', '1° Horário - Manhã'), ('2° Horário - Manhã', '2° Horário - Manhã'), ('3° Horário - Manhã', '4° Horário - Manhã'), ('4° Horário - Manhã', '4° Horário - Manhã'), ('5° Horário - Manhã', '5° Horário - Manhã'), ('6° Horário - Manhã', '6° Horário - Manhã'), ('1° Horário - Tarde', '1° Horário - Tarde'), ('2° Horário - Tarde', '2° Horário - Tarde'), ('3° Horário - Tarde', '4° Horário - Tarde'), ('4° Horário - Tarde', '4° Horário - Tarde'), ('5° Horário - Tarde', '5° Horário - Tarde'), ('6° Horário - Tarde', '6° Horário - Tarde'), ('1° Horário - Noite', '1° Horário - Noite'), ('2° Horário - Noite', '2° Horário - Noite'), ('3° Horário - Noite', '3° Horário - Noite'), ('4° Horário - Noite', '4° Horário - Noite')], default='2° Horário - Manhã', max_length=18)),
                ('justificativa', models.TextField()),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservarSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora_Atual', models.DateTimeField()),
                ('horario_de_Entrada', models.CharField(choices=[('1° Horário - Manhã', '1° Horário - Manhã'), ('2° Horário - Manhã', '2° Horário - Manhã'), ('3° Horário - Manhã', '4° Horário - Manhã'), ('4° Horário - Manhã', '4° Horário - Manhã'), ('5° Horário - Manhã', '5° Horário - Manhã'), ('6° Horário - Manhã', '6° Horário - Manhã'), ('1° Horário - Tarde', '1° Horário - Tarde'), ('2° Horário - Tarde', '2° Horário - Tarde'), ('3° Horário - Tarde', '4° Horário - Tarde'), ('4° Horário - Tarde', '4° Horário - Tarde'), ('5° Horário - Tarde', '5° Horário - Tarde'), ('6° Horário - Tarde', '6° Horário - Tarde'), ('1° Horário - Noite', '1° Horário - Noite'), ('2° Horário - Noite', '2° Horário - Noite'), ('3° Horário - Noite', '3° Horário - Noite'), ('4° Horário - Noite', '4° Horário - Noite')], default='1° Horário - Manhã', max_length=18)),
                ('horario_de_Saida', models.CharField(choices=[('1° Horário - Manhã', '1° Horário - Manhã'), ('2° Horário - Manhã', '2° Horário - Manhã'), ('3° Horário - Manhã', '4° Horário - Manhã'), ('4° Horário - Manhã', '4° Horário - Manhã'), ('5° Horário - Manhã', '5° Horário - Manhã'), ('6° Horário - Manhã', '6° Horário - Manhã'), ('1° Horário - Tarde', '1° Horário - Tarde'), ('2° Horário - Tarde', '2° Horário - Tarde'), ('3° Horário - Tarde', '4° Horário - Tarde'), ('4° Horário - Tarde', '4° Horário - Tarde'), ('5° Horário - Tarde', '5° Horário - Tarde'), ('6° Horário - Tarde', '6° Horário - Tarde'), ('1° Horário - Noite', '1° Horário - Noite'), ('2° Horário - Noite', '2° Horário - Noite'), ('3° Horário - Noite', '3° Horário - Noite'), ('4° Horário - Noite', '4° Horário - Noite')], default='2° Horário - Manhã', max_length=18)),
                ('justificativa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('bloco', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('h1_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h2_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h3_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h4_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h5_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h6_Matutino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h1_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h2_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h3_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h4_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h5_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h6_Vespertino', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h1_Noturno', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h2_Noturno', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h3_Noturno', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
                ('h4_Noturno', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='reservarsala',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sala'),
        ),
        migrations.AddField(
            model_name='reservarsala',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
