# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_material_j1_manha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='h1_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='07:00 - 07:45'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h2_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='07:45 - 08:30'),
        ),
    ]
