# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171202_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservarmaterial',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Deferido', 'Deferido'), ('Indeferido', 'Indeferido')], default='Aguardando', max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='h1_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='07:00 - 07:45'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h1_Noturno',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='19:00 - 19:45'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h1_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='13:00 - 13:45'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h2_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='07:45 - 08:30'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h2_Noturno',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='19:45 - 20:00'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h2_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='13:45 - 14:30'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h3_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='08:50 - 09:35'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h3_Noturno',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='20:45 - 21:30'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h3_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='14:50 - 15:35'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h4_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='09:35 - 10:20'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h4_Noturno',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='21:30 - 22:15'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h4_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='15:35 - 16:20'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h5_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='10:30 - 11:15'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h5_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='16:30 - 17:15'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h6_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='11:15 - 12:00'),
        ),
        migrations.AlterField(
            model_name='material',
            name='h6_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='17:15 - 18:00'),
        ),
        migrations.AlterField(
            model_name='reservarmaterial',
            name='horario_de_Entrada',
            field=models.CharField(choices=[('1° Horário - Manhã', '1° Horário - Manhã'), ('2° Horário - Manhã', '2° Horário - Manhã'), ('3° Horário - Manhã', '3° Horário - Manhã'), ('4° Horário - Manhã', '4° Horário - Manhã'), ('5° Horário - Manhã', '5° Horário - Manhã'), ('6° Horário - Manhã', '6° Horário - Manhã'), ('1° Horário - Tarde', '1° Horário - Tarde'), ('2° Horário - Tarde', '2° Horário - Tarde'), ('3° Horário - Tarde', '3° Horário - Tarde'), ('4° Horário - Tarde', '4° Horário - Tarde'), ('5° Horário - Tarde', '5° Horário - Tarde'), ('6° Horário - Tarde', '6° Horário - Tarde'), ('1° Horário - Noite', '1° Horário - Noite'), ('2° Horário - Noite', '2° Horário - Noite'), ('3° Horário - Noite', '3° Horário - Noite'), ('4° Horário - Noite', '4° Horário - Noite')], default='1° Horário - Manhã', max_length=18),
        ),
        migrations.AlterField(
            model_name='reservarmaterial',
            name='horario_de_Saida',
            field=models.CharField(choices=[('1° Horário - Manhã', '1° Horário - Manhã'), ('2° Horário - Manhã', '2° Horário - Manhã'), ('3° Horário - Manhã', '3° Horário - Manhã'), ('4° Horário - Manhã', '4° Horário - Manhã'), ('5° Horário - Manhã', '5° Horário - Manhã'), ('6° Horário - Manhã', '6° Horário - Manhã'), ('1° Horário - Tarde', '1° Horário - Tarde'), ('2° Horário - Tarde', '2° Horário - Tarde'), ('3° Horário - Tarde', '3° Horário - Tarde'), ('4° Horário - Tarde', '4° Horário - Tarde'), ('5° Horário - Tarde', '5° Horário - Tarde'), ('6° Horário - Tarde', '6° Horário - Tarde'), ('1° Horário - Noite', '1° Horário - Noite'), ('2° Horário - Noite', '2° Horário - Noite'), ('3° Horário - Noite', '3° Horário - Noite'), ('4° Horário - Noite', '4° Horário - Noite')], default='2° Horário - Manhã', max_length=18),
        ),
        migrations.AlterField(
            model_name='reservarsala',
            name='horario_de_Entrada',
            field=models.CharField(choices=[('1° Horário - Manhã', '1° Horário - Manhã'), ('2° Horário - Manhã', '2° Horário - Manhã'), ('3° Horário - Manhã', '3° Horário - Manhã'), ('4° Horário - Manhã', '4° Horário - Manhã'), ('5° Horário - Manhã', '5° Horário - Manhã'), ('6° Horário - Manhã', '6° Horário - Manhã'), ('1° Horário - Tarde', '1° Horário - Tarde'), ('2° Horário - Tarde', '2° Horário - Tarde'), ('3° Horário - Tarde', '3° Horário - Tarde'), ('4° Horário - Tarde', '4° Horário - Tarde'), ('5° Horário - Tarde', '5° Horário - Tarde'), ('6° Horário - Tarde', '6° Horário - Tarde'), ('1° Horário - Noite', '1° Horário - Noite'), ('2° Horário - Noite', '2° Horário - Noite'), ('3° Horário - Noite', '3° Horário - Noite'), ('4° Horário - Noite', '4° Horário - Noite')], default='1° Horário - Manhã', max_length=18),
        ),
        migrations.AlterField(
            model_name='reservarsala',
            name='horario_de_Saida',
            field=models.CharField(choices=[('1° Horário - Manhã', '1° Horário - Manhã'), ('2° Horário - Manhã', '2° Horário - Manhã'), ('3° Horário - Manhã', '3° Horário - Manhã'), ('4° Horário - Manhã', '4° Horário - Manhã'), ('5° Horário - Manhã', '5° Horário - Manhã'), ('6° Horário - Manhã', '6° Horário - Manhã'), ('1° Horário - Tarde', '1° Horário - Tarde'), ('2° Horário - Tarde', '2° Horário - Tarde'), ('3° Horário - Tarde', '3° Horário - Tarde'), ('4° Horário - Tarde', '4° Horário - Tarde'), ('5° Horário - Tarde', '5° Horário - Tarde'), ('6° Horário - Tarde', '6° Horário - Tarde'), ('1° Horário - Noite', '1° Horário - Noite'), ('2° Horário - Noite', '2° Horário - Noite'), ('3° Horário - Noite', '3° Horário - Noite'), ('4° Horário - Noite', '4° Horário - Noite')], default='2° Horário - Manhã', max_length=18),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h1_Noturno',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='19:00 - 19:45'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h1_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='13:00 - 13:45'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h2_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='07:45 - 08:30'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h2_Noturno',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='19:45 - 20:00'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h2_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='13:45 - 14:30'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h3_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='08:50 - 09:35'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h3_Noturno',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='20:45 - 21:30'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h3_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='14:50 - 15:35'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h4_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='09:35 - 10:20'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h4_Noturno',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='21:30 - 22:15'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h4_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='15:35 - 16:20'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h5_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='10:30 - 11:15'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h5_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='16:30 - 17:15'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h6_Matutino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='11:15 - 12:00'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='h6_Vespertino',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=12, verbose_name='17:15 - 18:00'),
        ),
    ]
