# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171120_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservarsala',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Deferido', 'Deferido'), ('Indeferido', 'Indeferido')], default='Aguardando', max_length=10),
        ),
    ]
