# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 23:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reservarsala_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservarmaterial',
            name='data_da_reserva',
            field=models.DateField(default=datetime.datetime(2017, 12, 9, 21, 37, 22, 731466)),
        ),
        migrations.AddField(
            model_name='reservarsala',
            name='data_da_reserva',
            field=models.DateField(default=datetime.datetime(2017, 12, 9, 21, 37, 22, 730463)),
        ),
    ]
